### ISSUE TITLE
Controls Issue

### ISSUE THREAD

**Issue by Coalition92** [ghostinthecamera/IGCS-GITC#13]
Sometimes when i tried to inject the dll, the camera controls altered what it was intended and i didn't change any controls of this. For example, when i press numpad 0, it switched to enable/disabel camera when by default it was pause/unpause. Can somebody explain this?

**Comment by ghostinthecamera** [comment]
Turn num lock on.

**Comment by bnthomason** [comment]
Hello! I have the latest version of this and the game. But when I attempt to inject the dll, the game crashes. I don't see any settings to tweak to make it work for v1.0.0. Do I need to grab the source code and compile it?

**Comment by Damphyre** [comment]
![image](https://user-images.githubusercontent.com/85460284/120940190-f691fa00-c713-11eb-922d-e3af91f42a80.png)
