### ISSUE TITLE
FF13 Doesn't work

### ISSUE THREAD

**Issue by DaddyWesker** [ghostinthecamera/IGCS-GITC#15]
Hello. 

Thanks for your app. Unfortunately, when i'm trying to use it among with FFXIII on steam game is just crashing. I'm launching FF13 first, then launching IGCSClient. pressing Inject DLL and then crash.

**Comment by ghostinthecamera** [comment]
Inject the tools once you have loaded in to the game. If you try and inject before you are in the game world it will crash the game.

**Comment by DaddyWesker** [comment]
Well, injected after loading. If i'm not pausing the game before injecting, it works. But sometimes game is just crashing the other way - sound is bugging, though i'm still can navigate camera using hotkeys, but not the characters... Well, at least it works somehow i guess.

**Comment by ghostinthecamera** [comment]
When you use the timestop in the tools (NUM 0) the sound will eventually sound distorted. That's just how it works. 

If you inject while the game is paused it will crash. 

What do you mean by not the characters?

I've been using the tools for weeks with 0 issues.

**Comment by DaddyWesker** [comment]
Yeah, but in my case, sound wont become normal again and i'm not able to control characters - only camera (and i've also wasnt able to resume the game). That's what i meant by "not the characters". I've faced that once. I'll try to see what causes that problem.

**Comment by ghostinthecamera** [comment]
You have to disable the camera by pressing INS again when you want to return to the game. 

You have to press NUM 0 again to unpause the game.

Are you saying you cannot disable the camera or unpause the game using the keys (INS and NUM 0)?

**Comment by DaddyWesker** [comment]
Yes, i wasnt able to unpause game with those keys.

**Comment by ghostinthecamera** [comment]
Check you haven't disabled NumLock. 

Otherwise, sorry, I've never experienced this issue, so cannot replicate it. It sounds like you have a problem with your keyboard registering keystrokes.

**Comment by DaddyWesker** [comment]
Well, not sure problem is in the keyboard =) I'll see if i can met same issue again and will get back to you.

**Comment by DaddyWesker** [comment]
So, i haven't met this problem again, so i'm closing the issue. If anything will happen, i'll get back to you. Thanks for the support.
