### ISSUE TITLE
Mutant Year Zero crashed when press num keypad '0' , when you reached later part of the game

### ISSUE THREAD

**Issue by kohweiteck** [ghostinthecamera/IGCS-GITC#26]
When you reached later part of the game (i.e : Lair of the Horned Devil / Metal Fields onwards) , the whole game crashes when you press num keypad 0 (in the camera roaming mode)  . Other keys worked (Like Numpad key and Camera Mode "Insert" )

**Comment by ghostinthecamera** [comment]
The Mutant Year Zero tools are quite old and out of date.

You're best bet is to use the Universal Unreal Unlocker (UUU) by Frans Bouma
