### ISSUE TITLE
Unable to move mouse, controls not correct

### ISSUE THREAD

**Issue by AmSqueakyBoi** [ghostinthecamera/IGCS-GITC#4]
After running AC7 and the injector as admin, waiting for the delay in startup to run the injector, my mouse is locked in the center of the screen, and I am unable to do anything with the overlay. There is nothing mentioned in the readme that says anything about dealing with this. In addition, my controls are not what the controls listed in the readme are. For example. The Numpad "." key is also my delete key, and toggles the hud off, instead of the listed tab. Any fix for this?

**Comment by ghostinthecamera** [comment]
So two things:
1) You cannot use the mouse in the menus in the game. This is true when the IGCS GUI is enabled when in the menus. If you open the IGCS GUI while in gameplay, it works fine. This is just the way it is.
2) Turn numlock on.
