### ISSUE TITLE
Game closes out when I toggle pause.

### ISSUE THREAD

**Issue by Hakuryu1984** [ghostinthecamera/IGCS-GITC#6]
When i push the zero key to toggle the pause, the game crashes. (This has happened on all missions, including the DLC one)

Activating the actual camera works fine, but i can't get the game to pause without the menu screen.

Any way to resolve this? Thank you.

**Comment by ghostinthecamera** [comment]
Game update has broken the tools.

If i get time i may update the tools otherwise there is no way to resolve this other than going to an older version of the game - sorry

**Comment by TheGrimCipher** [comment]
Well I'll be looking forward to the update. Love your tool man! It's a must for epic screenshots.
But hey no pressur or anything, take your time of course! I'll be patient :D
