### ISSUE TITLE
AC7: Cursor stuck to center of screen when Camera tools window is open

### ISSUE THREAD

**Issue by marathon1122** [ghostinthecamera/IGCS-GITC#7]
![New Bitmap Image](https://user-images.githubusercontent.com/56057430/66014069-72e22d80-e49b-11e9-950d-971cebd163db.jpg)

I can't select or change any settings in the camera tools menu because the cursor won't leave the center of the screen

**Comment by ghostinthecamera** [comment]
The game takes control of the mouse in menus. It returns control of the mouse when in gameplay. Unfortunately, there is nothing I can do about this. You will have to adjust the settings in game.
